export const CLUBS = [
  "Manchester United", "Manchester City", "Liverpool", "Chelsea", "Arsenal",
  "Tottenham Hotspur", "Leicester City", "West Ham United", "Everton", "Aston Villa",
  "Newcastle United", "Wolverhampton Wanderers", "Brighton & Hove Albion", "Crystal Palace",
  "Brentford", "Fulham", "Bournemouth", "Nottingham Forest", "Burnley", "Sheffield United",
  "Real Madrid", "Barcelona", "Atletico Madrid", "Sevilla", "Real Betis",
  "Real Sociedad", "Villarreal", "Athletic Bilbao", "Valencia", "Girona",
  "Bayern Munich", "Borussia Dortmund", "RB Leipzig", "Bayer Leverkusen",
  "Eintracht Frankfurt", "Wolfsburg", "Freiburg", "Union Berlin", "Stuttgart",
  "Paris Saint-Germain", "Olympique Marseille", "Lyon", "Monaco", "Lille",
  "Juventus", "AC Milan", "Inter Milan", "Napoli", "AS Roma", "Lazio", "Atalanta", "Fiorentina",
  "Ajax", "PSV Eindhoven", "Feyenoord",
  "Porto", "Benfica", "Sporting CP",
  "Celtic", "Rangers",
  "Galatasaray", "Fenerbahce", "Besiktas",
  "Al Hilal", "Al Nassr", "Al Ahli", "Al Ittihad",
  "Flamengo", "Palmeiras", "Santos", "Corinthians", "São Paulo",
  "River Plate", "Boca Juniors",
  "Club América", "Guadalajara",
  "LA Galaxy", "Inter Miami", "Atlanta United", "Seattle Sounders", "LAFC",
  "Toronto FC", "New York City FC", "New York Red Bulls",
  "Olympiacos", "PAOK", "AEK Athens",
  "Anderlecht", "Club Brugge",
  "Red Bull Salzburg", "Rapid Wien",
  "Young Boys", "FC Basel",
  "Dinamo Zagreb", "Hajduk Split",
  "Shakhtar Donetsk", "Dynamo Kyiv",
  "Zenit Saint Petersburg", "CSKA Moscow", "Spartak Moscow",
  "Al Ahly", "Zamalek",
  "Mamelodi Sundowns", "Kaizer Chiefs", "Orlando Pirates"
];